### ISSUE TITLE
怎么让一个 div 水平垂直居中

### ISSUE THREAD

**Issue by lovelmh13** [lovelmh13/One-question-a-day#25]
我只写出来了常用的，黑科技滴没有
**不规定子元素宽高的时候（有宽高自然也可以用）：**
1. transorm
```html
<style>
	.shell {
		width: 200px;
		height: 200px;
		border: 1px solid red;
		position: relative;
	}
	.box {
		background: #fdcaed;
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
	}
</style>

<div class="shell">
	<div class="box">asdfasdgfawsdfasdfasdf</div>
</div>
```

2. flex
```css
.shell {
	width: 200px;
	height: 200px;
	border: 1px solid red;
	display: flex;
	align-items: center;
	justify-content: center;
}
.box {
	background: #fdcaed;
}
```
3. grid
```css
.shell {
	width: 200px;
	height: 200px;
	border: 1px solid red;
	display: grid;
	align-content: center;
	justify-content: center;
}
.box {
	background: #fdcaed;
}
```
**给定宽高**
```css
.shell {
	width: 200px;
	height: 200px;
	border: 1px solid red;
	position: relative;
}
.box {
	width: 100px;
	height: 100px;
	background: #fdcaed;
	position: absolute;
	top: 50%;
	left: 50%;
	margin-top: -50px;
	margin-left: -50px;
}
```
